### ISSUE TITLE
what the CPU_PORT should be for barefoot tna switch?

### ISSUE THREAD

**Issue by daniel0720** [Dscano/Basic-tna#2]
Hello，what the CPU_PORT should be for barefoot tna switch?
In the define.p4，the CPU_PORT is left blank，while in the constants.java，for bmv2 switch，the CPU_PORT is 255，for tofino switch，TNA model，the cpu_PORT is 0xFFFFFFFD。but in define.p4，CPU_PORT is 9 bit width.

**Comment by Dscano** [comment]
Hi @daniel0720 ,

- you can use the exact value of the CPU_PORT, according to your box, and write it in the p4 program.
- you can use at control plane th CPU_PORT value 0xFFFFFFFD, as is done in farbric-tna

**Comment by daniel0720** [comment]
@Dscano Thank you for your reply.
As what you said，the value of CPU_PORT in the p4 file and the onos java file can be different？

**Comment by daniel0720** [comment]
How to make Basic-tna work?
I set the CPU_PORT to 192, according to my box.
In my experiment, only one barefoot switch connected to two hosts. Port 3/0 and 3/1
![image](https://user-images.githubusercontent.com/12429142/210729017-dd7b5767-8bdb-4e79-8ee5-ae4849bdb74f.png)

The activated apps is as follows, including fwd, hostprovider, lldpprovider.
![image](https://user-images.githubusercontent.com/12429142/210728729-6f64b29c-c3fa-4e49-b26a-1c64ae7cba37.png)

The flow rules is as follows.
![image](https://user-images.githubusercontent.com/12429142/210728861-58baeca3-0b08-4ccb-bea2-5532451007ba.png)

But when I ping from one host to another, It cannot work.
Is there anything I missed?

**Comment by Dscano** [comment]
@daniel0720,

I think that you have to activate another onos app called arp resolution or something like that, but i'm not 100% sure.
 Seems that no flow rules are installed by fwd in order to forward the traffic, you can try to install 2 flow rules by hand via REST ( http://<ONOS IP>:8181/onos/v1/docs/.) https://wiki.onosproject.org/display/ONOS/Flow+Rules.

Did you try to snif the traffic among the host and the switch?

**Comment by daniel0720** [comment]
@Dscano 
I insert mac address of two host by hand in each host. so no arp resolution needed. but it still does not work. The app fwd insert one flow rule named 
ADDED, bytes=82092, packets=785, table=BasicIngress.table0.table0, priority=5, selector=[ETH_TYPE:ipv4], treatment=[immediate=[BasicIngress.table0.copy_to_cpu()]]
but there is no set_egress_port flow rule.

**Comment by Dscano** [comment]
Hi, 
the fwd app should also install 2 flow rules to enable the forwarding among the 2 host. This flow rule is ok: ADDED, bytes=82092, packets=785, table=BasicIngress.table0.table0, priority=5, selector=[ETH_TYPE:ipv4], treatment=[immediate=[BasicIngress.table0.copy_to_cpu()]] and should used by the controller to handle ipv4 traffic that does not match any flow rule in the data plane.

**Comment by daniel0720** [comment]
But the fwd app does not install 2 flow rules and I don't know why. How to solve the problem? Where can I start to find why?

**Comment by Dscano** [comment]
You can push by hand the flow rules via REST in order to verify that everything works, than you can start to do troubleshooting via the onos logs.

**Comment by daniel0720** [comment]
@Dscano OK，thank you very much. Really appreciate your help.

**Comment by endrigoshi** [comment]
Hi @daniel0720 

Did you manage to solve the issue? I also cannot send packets to CPU_PORT, hence I do not see any l2-forwarding rules being installed in the switch.
Although I think there are some bugs in the code, e.g.:
- https://github.com/Dscano/Basic-tna/blob/4b5d54036cf37b6f3be3fc74409ff9aca9d7c83e/p4src/tna/include/control/table0.p4#L22 here the drop flag is being set to 1, and therefore the PacketIn is being dropped.
- PacketIoEgress is not applied to any packets, unline PacketIoIngress that is being applied in https://github.com/Dscano/Basic-tna/blob/4b5d54036cf37b6f3be3fc74409ff9aca9d7c83e/p4src/tna/basic_tna.p4#L29

However, even after altering the behavior, I still do not see any packets on the ONOS side.

Best regards,
Endri
