### ISSUE TITLE
How to add a flow table

### ISSUE THREAD

**Issue by knightswim** [Dscano/Basic-tna#3]
I don't know how to add a flow table. Can you give me an example of JSON?

**Comment by Dscano** [comment]
Hi @knightswim,

You can go to http://<ONOS IP>:8181/onos/v1/docs/ and there you find the REST calls aviable.
Here you can find how you can compose a JSON  https://wiki.onosproject.org/display/ONOS/Flow+Rules, pay attention because the flow rules that you are going to push in the device must be consisten with the P4 pipeline.

Here a simple example:
```
{
  "priority": 40000,
  "timeout": 0,
  "isPermanent": true,
  "deviceId": "of:0000000000000001",
  "treatment": {
    "instructions": [
      {
        "type": "OUTPUT",
        "port": "3"
      }
    ]
  },
  "selector": {
    "criteria": [
      {
        "type": "IN_PORT",
        "port": "1"
      }
    ]
  }
}
```

**Comment by knightswim** [comment]
ADDED, bytes=82092, packets=785, table=BasicIngress.table0.table0, priority=5, selector=[ETH_TYPE:ipv4], treatment=[immediate=[BasicIngress.table0.copy_to_cpu()]]    Can you help translate the basic flow table into JSON

**Comment by Dscano** [comment]
```
{
  "priority": 5,
  "timeout": 0,
  "isPermanent": true,
  "deviceId": "of:0000000000000001",
  "treatment": {
    "instructions": [
      {
        "type": "OUTPUT",
        "port": "CPU_PORT"
      }
    ]
  },
  "selector": {
    "criteria": [
      {
        "type": "ETH_TYPE",
        "ethType": "0x0800"
      },
    ]
  }
}
```

**Comment by knightswim** [comment]
Unable to INSERT table entry on device:leaf-1: OTHER_ERROR INVALID_ARGUMENT RET_CHECK failure (stratum/hal/lib/barefoot/bfrt_p4runtime_translator.cc:688) 'singleton_port_to_sdk_port_.contains(port_id)' is false. Could not find SDK port for singleton port 192. (:503) [PiTableEntry{tableId=BasicIngress.table0.table0, matchKey={eth_type=0x800&&&0xffff}, tableAction=BasicIngress.table0.set_egress_port(port_num=0xc0), priority=6, timeout=PERMANENT}]   There are some mistakes, can you help me take a look

**Comment by Dscano** [comment]
Try something like that 
```
{
  "priority": 5,
  "timeout": 0,
  "isPermanent": true,
  "deviceId": "of:0000000000000001",
  "treatment": {
    "instructions": [
      {
        "type": "BASIC_INGRESS_TABLE0_COPY_TO_CPU",
        "port": "CONTROLLER"
      }
    ]
  },
  "selector": {
    "criteria": [
      {
        "type": "ETH_TYPE",
        "ethType": "0x0800"
      },
    ]
  }
}
```

**Comment by knightswim** [comment]
{
  "code": 400,
  "message": "Instruction type BASIC_INGRESS_TABLE0_COPY_TO_CPU is not supported"
}    There are still some errors

**Comment by Dscano** [comment]
could be COPY_TO_CPU, but i think that you get the flavor for writing a flow rule
